CREATE DATABASE QLBANTSa1
go
use QLBANTSa1
go
CREATE TABLE BAN(
	MABAN	INT	IDENTITY(1,1)	not null,
	TENBAN NVARCHAR(50) NULL,
	SONGUOINGOIMAX INT NULL,
	TRANGTHAI INT NULL,
	CONSTRAINT BAN_PK PRIMARY KEY (MABAN)
)
insert into ban(tenban,songuoingoimax,trangthai) values(N'Bàn 1',10,0)
insert into ban(tenban,songuoingoimax,trangthai) values(N'Bàn 2',5,0)
insert into ban(tenban,songuoingoimax,trangthai) values(N'Bàn 3',10,0)
insert into ban(tenban,songuoingoimax,trangthai) values(N'Bàn 4',8,0)

CREATE TABLE KHUYENMAI(
	MAKM	INT	IDENTITY(1,1) NOT NULL,
	TENKM NVARCHAR(50) NULL,
	SOTIENKM MONEY NULL,
	NGAYBD DATE NULL,
	NGAYKT DATETIME NULL,
	TRANGTHAI INT NULL,	
	CONSTRAINT KHUYENMAI_PK PRIMARY KEY (MAKM)
)

INSERT INTO KHUYENMAI(TENKM,SOTIENKM,NGAYBD,NGAYKT,TRANGTHAI) VALUES('KM1',1000,'2022-12-12','2022-12-16',1)
INSERT INTO KHUYENMAI(TENKM,SOTIENKM,NGAYBD,NGAYKT,TRANGTHAI) VALUES('KM2',2000,'2022-12-12','2022-12-16',1)
INSERT INTO KHUYENMAI(TENKM,SOTIENKM,NGAYBD,NGAYKT,TRANGTHAI) VALUES('KM3',3000,'2022-12-12','2022-12-16',1)
INSERT INTO KHUYENMAI(TENKM,SOTIENKM,NGAYBD,NGAYKT,TRANGTHAI) VALUES('Không Sale',0,'2022-12-12','2023-12-12',1)

CREATE TABLE CHUCVU(
	MACV	INT	IDENTITY(1,1)NOT NULL,
	TECV NVARCHAR(50) NULL,
	CONSTRAINT CHUCVU_PK PRIMARY KEY (MACV)
)
insert into CHUCVU(tecv) values(N'Nhân Viên')
insert into CHUCVU(tecv) values(N'Quản Lý')

CREATE TABLE NCC(
	MANCC	INT	IDENTITY(1,1)NOT NULL,
	TENNCC NVARCHAR(50) NULL,
	DIACHI NVARCHAR(50) NULL,
	SDT NVARCHAR(10) NULL,
	CONSTRAINT NCC_PK PRIMARY KEY (MANCC)
)
insert into NCC(TENNCC,DIACHI,SDT) values(N'Thành Danh',N'Hà Nội','0385090080')
insert into NCC(TENNCC,DIACHI,SDT) values(N'Thanh Tuấn',N'Thanh Hóa','0385090081')
insert into NCC(TENNCC,DIACHI,SDT) values(N'Đình Quân',N'Nam Định','0385090082')

CREATE TABLE NGUYENLIEU(
	MANL	INT	IDENTITY(1,1) NOT NULL,
	TENNL NVARCHAR(50) NULL,
	MOTA NVARCHAR(50) NULL,
	CONSTRAINT NGUYENLIEU_PK PRIMARY KEY (MANL)
)
insert into NGUYENLIEU(TENNL,MOTA) values(N'Sữa',N'Chính Hãng')
insert into NGUYENLIEU(TENNL,MOTA) values(N'Trân Châu',N'Hàng Quảng Châu')
insert into NGUYENLIEU(TENNL,MOTA) values(N'Đường',N'Ngọt')


CREATE TABLE USERTT(
	MANV	INT	IDENTITY(1,1) NOT NULL,
	MACV INT NULL,
	HOTEN NVARCHAR(50) NULL,
	GIOITINH NVARCHAR(20) NULL,
	NAMSINH INT NULL,
	DIACHI NVARCHAR(50) NULL,
	CCCD NVARCHAR(12) NULL,
	SDT NVARCHAR(10) NULL,
	TAIKHOAN NVARCHAR(50) unique NULL,
	MATKHAU NVARCHAR(50) NULL,
	TRANGTHAI INT NULL,
	CONSTRAINT USERTT_FK FOREIGN KEY (MACV) REFERENCES CHUCVU,
	CONSTRAINT USERTT_PK PRIMARY KEY (MANV)
)

insert into USERTT(macv,HOTEN,gioitinh,namsinh,diachi,cccd,sdt,taikhoan,matkhau,trangthai) values(1,N'Đức Đạt',N'Nam',2003,N'Hà Nội','001203042247','0357212978','nhanvien','nhanvien',1)
insert into USERTT(macv,HOTEN,gioitinh,namsinh,diachi,cccd,sdt,taikhoan,matkhau,trangthai) values(1,N'Nguyễn Phượng',N'Nữ',2003,N'Hà Nội','001203042248','0357212979','nhanvien1','nhanvien1',1)
insert into USERTT(macv,HOTEN,gioitinh,namsinh,diachi,cccd,sdt,taikhoan,matkhau,trangthai) values(2,N'Nguyễn Danh',N'Nam',2003,N'Hà Nội','001203042249','0357212980','quanly','quanly',1)


CREATE TABLE GIAOCA(
	MACA	INT	IDENTITY(1,1) PRIMARY KEY	not null,
	THOIGIANNHANCA DATETIME NULL,
	THOIGIANGIAOCA DATETIME NULL,
	MANHANVIENTRONGCA INT NULL,
	MANHANVIENNHANCA INT NULL,
	TIENBANDAU MONEY NULL,
	TONGTIENTRONGCA MONEY NULL,
	THOIGIANRESET DATETIME NULL,
	MAQUANLIRESET INT NULL,
	TONGTIENRUT MONEY NULL,
	TRANGTHAI INT NULL,
	FOREIGN KEY (MANHANVIENTRONGCA) REFERENCES USERTT,
	FOREIGN KEY (MANHANVIENNHANCA) REFERENCES USERTT,
	FOREIGN KEY (MAQUANLIRESET) REFERENCES USERTT,
)

insert into GIAOCA(THOIGIANNHANCA,THOIGIANGIAOCA,TIENBANDAU,TONGTIENTRONGCA,TRANGTHAI) values(GETDATE(),GETDATE(),1000000,1000000,0)

CREATE TABLE KHACHHANG(
	MAKH	INT	IDENTITY(1,1)	PRIMARY KEY,
	TENKH NVARCHAR(20) NULL,
	DIACHI NVARCHAR(20) NULL,
	SDT NVARCHAR(20) NULL,
)

insert into KHACHHANG(TENKH,DIACHI,SDT) values(N'Nguyễn Quốc',N'Hà Nội','0385090080')
insert into KHACHHANG(TENKH,DIACHI,SDT) values(N'Nguyễn Tuấn',N'Hà Nội','0385090081')
insert into KHACHHANG(TENKH,DIACHI,SDT) values(N'Nguyễn Hoa',N'Hà Nội','0385090082')

CREATE TABLE SANPHAM(
	MASP	INT	IDENTITY(1,1) NOT NULL,
	MAKM INT NULL,
	TENSP NVARCHAR(50) NULL,
	ANHSP VARCHAR(150) NULL,
	GIABAN MONEY NULL,
	TRANGTHAI INT NULL,
	FOREIGN KEY (MAKM) REFERENCES KHUYENMAI,
	CONSTRAINT SANPHAM_PK PRIMARY KEY (MASP)
)

INSERT INTO SANPHAM(MAKM,TENSP,ANHSP,GIABAN,TRANGTHAI) VALUES(1,N'Trà Đào','D:\DUAN1\BanTraSua_HT\src\main\java\poly\nhom4\img\1.png',10000,0)
INSERT INTO SANPHAM(MAKM,TENSP,ANHSP,GIABAN,TRANGTHAI) VALUES(2,N'Trà Bưởi','D:\DUAN1\BanTraSua_HT\src\main\java\poly\nhom4\img\1.png',20000,0)
INSERT INTO SANPHAM(MAKM,TENSP,ANHSP,GIABAN,TRANGTHAI) VALUES(3,N'Trà Cam','D:\DUAN1\BanTraSua_HT\src\main\java\poly\nhom4\img\2.png',30000,0)
INSERT INTO SANPHAM(MAKM,TENSP,ANHSP,GIABAN,TRANGTHAI) VALUES(1,N'Trà Chanh','D:\DUAN1\BanTraSua_HT\src\main\java\poly\nhom4\img\3.png',40000,0)
INSERT INTO SANPHAM(MAKM,TENSP,ANHSP,GIABAN,TRANGTHAI) VALUES(4,N'Tra Táo','D:\DUAN1\BanTraSua_HT\src\main\java\poly\nhom4\img\3.png',50000,0)

CREATE TABLE HOADON(
	MAHD INT	IDENTITY(1,1)NOT NULL,
	MANV INT NULL,
	MAKH INT NULL,
	TINHTRANG INT NULL,
	NGAYTAO DATETIME NULL,
	FOREIGN KEY (MANV) REFERENCES USERTT,
	FOREIGN KEY (MAKH) REFERENCES KHACHHANG,		
	CONSTRAINT HOADON_PK PRIMARY KEY (MAHD)
)
insert into hoadon(manv,makh,tinhtrang,ngaytao) values(1,2,1,'2022-12-7')
insert into hoadon(manv,makh,tinhtrang,ngaytao) values(2,3,1,'2022-12-8')
insert into hoadon(manv,makh,tinhtrang,ngaytao) values(2,2,0,'2022-12-14')
insert into hoadon(manv,makh,tinhtrang,ngaytao) values(1,1,0,'2022-12-14')
CREATE TABLE HOADONCHITIET(
	MAHOADONCT	INT	IDENTITY(1,1) NOT NULL,
	MAHD INT  null,
	MASP INT  NULL,
	MABAN INT  NULL,
	SOLUONG INT NULL,
	DONGIA MONEY NULL,
	MOTA NVARCHAR(50) null,
	FOREIGN KEY (MASP) REFERENCES SANPHAM,
	FOREIGN KEY (MABAN) REFERENCES BAN,	
	FOREIGN KEY (MAHD) REFERENCES HOADON,
	CONSTRAINT HOADONCHITIET_PK PRIMARY KEY (MAHOADONCT) 
)
SELECT * FROM HOADON
insert into HOADONCHITIET(MAHD,MABAN,SOLUONG) values(1,1,0)
insert into HOADONCHITIET(MAHD,MABAN,SOLUONG) values(1,2,0)
insert into HOADONCHITIET(MAHD,MABAN,SOLUONG) values(2,2,0)
insert into HOADONCHITIET(MAHD,MABAN,SOLUONG) values(2,3,0)
insert into HOADONCHITIET(MAHD,MABAN,SOLUONG) values(3,2,0)
insert into HOADONCHITIET(MAHD,MABAN,SOLUONG) values(4,1,0)
insert into HOADONCHITIET(MAHD,MABAN,SOLUONG) values(4,2,0)
insert into HOADONCHITIET(MAHD,MASP,SOLUONG,DONGIA) values(1,1,5,10000)
insert into HOADONCHITIET(MAHD,MASP,SOLUONG,DONGIA) values(1,2,4,20000)
insert into HOADONCHITIET(MAHD,MASP,SOLUONG,DONGIA) values(2,2,6,20000)
insert into HOADONCHITIET(MAHD,MASP,SOLUONG,DONGIA) values(2,3,7,30000)
SELECT * FROM HOADONCHITIET

CREATE TABLE HOADONNHAPNL(
	MAHDNNL	INT	IDENTITY(1,1)NOT NULL,
	MANV INT NULL,
	NGAYNHAP DATE NULL,
	FOREIGN KEY (MANV) REFERENCES USERTT,	
	CONSTRAINT HOADONNHAPNL_PK PRIMARY KEY (MAHDNNL)
)
insert into HOADONNHAPNL(MANV,NGAYNHAP) values(2,'2022-12-10')
insert into HOADONNHAPNL(MANV,NGAYNHAP) values(1,'2022-12-9')
insert into HOADONNHAPNL(MANV,NGAYNHAP) values(2,'2022-12-8')
