/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poly.nhom4.view;

import poly.nhom4.domainmodel.ChucVu;
import poly.nhom4.reponse.ChucVuReponse;
import poly.nhom4.reponse.UserTTReponse;
import poly.nhom4.service.ChucVuService;
import poly.nhom4.service.UserTTService;
import poly.nhom4.service.impl.ChucVuServiceImpl;
import poly.nhom4.service.impl.UserTTServiceIplm;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.DefaultButtonModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FPT Shop
 */
public class NhanVienView extends javax.swing.JFrame {

    /**
     * Creates new form DangKyForm
     */
    private UserTTService userTTService = new UserTTServiceIplm();
    private ChucVuService chucVuService = new ChucVuServiceImpl();
    private DefaultComboBoxModel defaultComboBoxModel;
    ButtonGroup buttonGroup;

    public NhanVienView() {
        initComponents();
        btnGroup();
        comboChucVu();
        loadata();
    }

    private void btnGroup() {
        buttonGroup = new ButtonGroup();
        buttonGroup.add(rd_nu);
        buttonGroup.add(rd_nam);
    }

    public void loadata() {
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
        defaultTableModel.setRowCount(0);
        List<UserTTReponse> lst = userTTService.getAllUserTTs();
        for (UserTTReponse x : lst) {
            defaultTableModel.addRow(new Object[]{
                x.getTaiKhoan(), x.getMatKhau(), x.getHoTen(), x.getGioiTinh(),
                x.getNamSinh(), x.getDiaChi(), x.getCccd(), x.getSdt(), x.getChucVu().getTENCV()
            });
        }
    }

    private void comboChucVu() {
        try {
            defaultComboBoxModel = (DefaultComboBoxModel) cb_chucVu.getModel();
            List<ChucVuReponse> list = chucVuService.getAllChucVus();
            for (ChucVuReponse chucVuReponse : list) {
                defaultComboBoxModel.addElement(chucVuReponse.getTenCV());
            }
            cb_chucVu.setSelectedIndex(1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi comboBox");            // cho form tạo chức vụ vào
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JPasswordField();
        btnDangKy = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_chucVu = new javax.swing.JComboBox<>();
        rd_nam = new javax.swing.JRadioButton();
        rd_nu = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtNamSinh = new javax.swing.JTextField();
        txtCCCD = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Goudy Stout", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ql nhân viên");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Tài khoản :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Mật khẩu : ");

        txtMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatKhauActionPerformed(evt);
            }
        });

        btnDangKy.setBackground(new java.awt.Color(204, 153, 255));
        btnDangKy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDangKy.setText("Đăng ký");
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Giới tính:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Họ Tên:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Năm sinh :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Địa chỉ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("SĐT");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("CCCD");

        cb_chucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_chucVuActionPerformed(evt);
            }
        });

        rd_nam.setText("Nam");

        rd_nu.setText("Nữ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Chức vụ");

        btnXoa.setBackground(new java.awt.Color(204, 153, 255));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapNhat.setBackground(new java.awt.Color(204, 153, 255));
        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Tài khoản", "Mật khẩu", "Họ tên", "Giới tính", "Năm sinh", "Địa chỉ", "SĐT", "CCCD", "Chức vụ"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rd_nam)
                                        .addGap(18, 18, 18)
                                        .addComponent(rd_nu))
                                    .addComponent(txtNamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnDangKy)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnXoa)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCapNhat)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cb_chucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rd_nam)
                    .addComponent(rd_nu)
                    .addComponent(jLabel10)
                    .addComponent(cb_chucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangKy)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatKhauActionPerformed

    private void cb_chucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_chucVuActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_cb_chucVuActionPerformed

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        // TODO add your handling code here:
        Integer namSinh = Integer.parseInt(txtNamSinh.getText().trim());
        if (txtCCCD.getText().trim().length() == 0 || txtDiaChi.getText().trim().length() == 0
                || txtHoTen.getText().trim().length() == 0
                || String.valueOf(txtMatKhau.getPassword()).trim().length() == 0
                || txtNamSinh.getText().trim().length() == 0
                || txtSDT.getText().trim().length() == 0
                || txtTaiKhoan.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không được để trống");
        } else if (txtCCCD.getText().trim().length() != 12) {
            JOptionPane.showMessageDialog(this, "Căn cước phải là 12 số");
        } else if (txtSDT.getText().trim().length() != 10) {
            JOptionPane.showMessageDialog(this, "SĐT phải là 10 số");
        } else if (namSinh < 1910 || namSinh > 2022) {
            JOptionPane.showMessageDialog(this, "Năm sinh không hợp lệ");
        } else {
            List<UserTTReponse> userTTReponses = userTTService.getAllUserTTs();
            UserTTReponse user = new UserTTReponse();
            user.setTaiKhoan(txtTaiKhoan.getText().trim());
            user.setMatKhau(String.valueOf(txtMatKhau.getPassword()).trim());
            String hoTen = txtHoTen.getText().trim();
            user.setHoTen(hoTen);
            if (rd_nam.isSelected()) {
                user.setGioiTinh("Nam");
            } else if (rd_nu.isSelected()) {
                user.setGioiTinh("Nữ");
            }
//            Integer namSinh = Integer.parseInt(txtNamSinh.getText().trim());
            String diaChi = txtDiaChi.getText().trim();
            String sdt = txtSDT.getText().trim();
            String cccd = txtCCCD.getText().trim();

            try {
                // lấy ra chức vụ
//                ChucVuReponse cv = (ChucVuReponse) cb_chucVu.getSelectedItem();
//                ChucVu chucVu = new ChucVu();
//                chucVu.setMACV(cv.getMaCV());
//                chucVu.setTENCV(cv.getTenCV());
//                user.setChucVu(chucVu);
                List<ChucVuReponse> list = chucVuService.getAllChucVus();
                for (ChucVuReponse chucVuReponse : list) {
                    if (chucVuReponse.getTenCV().equalsIgnoreCase(cb_chucVu.getSelectedItem().toString().trim())) {
                        ChucVu chucVu = new ChucVu();
                        chucVu.setMACV(chucVuReponse.getMaCV());
                        chucVu.setTENCV(chucVuReponse.getTenCV());
                        user.setChucVu(chucVu);
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Vui lòng tạo chức vụ");
            }

            user.setTrangThai(1);
//            String ns = String.valueOf(namSinh);
            user.setNamSinh(namSinh);
            user.setDiaChi(diaChi);
            user.setSdt(sdt);
            user.setCccd(cccd);
            boolean kq = userTTService.insertUser(user);
            if (kq == true) {
                JOptionPane.showMessageDialog(this, "Đăng ký thành công");
                loadata();
            } else {
                JOptionPane.showMessageDialog(this, "Nhân viên đã tồn tại");
            }
        }
    }//GEN-LAST:event_btnDangKyActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 dòng");
        } else {
            int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không", "Xóa", 0);
            if (choice == JOptionPane.YES_OPTION) {
                UserTTReponse reponse = userTTService.getAllUserTTs().get(row);
                userTTService.delete(reponse);
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                loadata();
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        Integer namSinh = Integer.parseInt(txtNamSinh.getText().trim());
        if (txtCCCD.getText().trim().length() == 0 || txtDiaChi.getText().trim().length() == 0
                || txtHoTen.getText().trim().length() == 0
                || String.valueOf(txtMatKhau.getPassword()).trim().length() == 0
                || txtNamSinh.getText().trim().length() == 0
                || txtSDT.getText().trim().length() == 0
                || txtTaiKhoan.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không được để trống");
        } else if (txtCCCD.getText().trim().length() != 12) {
            JOptionPane.showMessageDialog(this, "Căn cước phải là 12 số");
        } else if (txtSDT.getText().trim().length() != 10) {
            JOptionPane.showMessageDialog(this, "SĐT phải là 10 số");
        } else if (namSinh < 1910 || namSinh > 2022) {
            JOptionPane.showMessageDialog(this, "Năm sinh không hợp lệ");
        } else {
            List<UserTTReponse> userTTReponses = userTTService.getAllUserTTs();
            int row = jTable1.getSelectedRow();
            Integer maNV = userTTReponses.get(row).getMaNV();
            for (UserTTReponse user : userTTReponses) {
                if (user.getMaNV().equals(maNV)) {
//                    UserTTReponse user = new UserTTReponse();
                    user.setTaiKhoan(txtTaiKhoan.getText().trim());
                    user.setMatKhau(String.valueOf(txtMatKhau.getPassword()).trim());
                    String hoTen = txtHoTen.getText().trim();
                    user.setHoTen(hoTen);
                    if (rd_nam.isSelected()) {
                        user.setGioiTinh("Nam");
                    } else if (rd_nu.isSelected()) {
                        user.setGioiTinh("Nữ");
                    }
//            Integer namSinh = Integer.parseInt(txtNamSinh.getText().trim());
                    String diaChi = txtDiaChi.getText().trim();
                    String sdt = txtSDT.getText().trim();
                    String cccd = txtCCCD.getText().trim();

                    try {
                        // lấy ra chức vụ
                        List<ChucVuReponse> list = chucVuService.getAllChucVus();
                        for (ChucVuReponse chucVuReponse : list) {
                            if (chucVuReponse.getTenCV().equalsIgnoreCase(cb_chucVu.getSelectedItem().toString().trim())) {
                                ChucVu chucVu = new ChucVu();
                                chucVu.setMACV(chucVuReponse.getMaCV());
                                chucVu.setTENCV(chucVuReponse.getTenCV());
                                user.setChucVu(chucVu);
                            }
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Vui lòng tạo chức vụ");
                    }

                    user.setTrangThai(1);
                    user.setNamSinh(namSinh);
                    user.setDiaChi(diaChi);
                    user.setSdt(sdt);
                    user.setCccd(cccd);

                    boolean kq = userTTService.updateUser(user);

                    if (kq == true) {
                        JOptionPane.showMessageDialog(this, "Sửa thành công");
                        loadata();
                    } else {
                        JOptionPane.showMessageDialog(this, "Sửa không thành công");
                    }
                }
            }

        }    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        txtTaiKhoan.setText(jTable1.getValueAt(row, 0).toString());
        txtMatKhau.setText(jTable1.getValueAt(row, 1).toString());
        txtHoTen.setText(jTable1.getValueAt(row, 2).toString());
        if (jTable1.getValueAt(row, 3).toString().equals("Nam")) {
            rd_nam.setSelected(true);
        } else if (jTable1.getValueAt(row, 3).toString().equals("Nữ")) {
            rd_nu.setSelected(true);
        } else {
            JOptionPane.showMessageDialog(this, "Không có giới tính");
        }
        txtNamSinh.setText(jTable1.getValueAt(row, 4).toString());
        txtDiaChi.setText(jTable1.getValueAt(row, 5).toString());
        txtSDT.setText(jTable1.getValueAt(row, 6).toString());
        txtCCCD.setText(jTable1.getValueAt(row, 7).toString());
        String getcv = jTable1.getValueAt(row, 8).toString();
        cb_chucVu.setSelectedItem(getcv);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVienView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnDangKy;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cb_chucVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rd_nam;
    private javax.swing.JRadioButton rd_nu;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtNamSinh;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
